name: FlutterTest
description: A new Flutter application.

dependencies:
  path_provider: ^0.4.1
  http: ^0.12.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  fluttertoast: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/flutter_img.jpg
    - images/img_1.jpg
    - images/img_2.jpg
    - images/img_3.jpg
    - images/img_4.jpg

  fonts:
    - family: global
      fonts:
        - asset: fonts/global.ttf
